### ISSUE TITLE
Tool doesn't work

### ISSUE THREAD

**Issue by Swaggymcmuffins** [joaen/maya-auto-lip-sync#12]
Hi all, I'm hoping someone could shed some light on my issue with this tool. I got as far as creating all of the files needed for the tool to theoretically work, and in theory it does work, just not fully. It imports the audio file onto the timeline, but does not create any keyframes with it, despite everything being "connected" to the right areas. I will try to add a short clip of this, if anyone has any idea what I may have done wrong, please do let me know as I really want/ need this tool to do its thing.

TIA
-Pabs[

https://github.com/joaen/maya-auto-lip-sync/assets/47432333/9adc38a0-5b84-4185-a720-33782b2854c8

](url)

**Comment by joaen** [comment]
Hi! Can you please share the error log from the Maya script editor?

**Comment by Swaggymcmuffins** [comment]
Of course! I do apologise I should have added it in the post, but here it is;

b"'mfa_align.exe' is not recognized as an internal or external command,\r\n"
b'operable program or batch file.\r\n'
# Traceback (most recent call last):
#   File "<maya console>", line 323, in generate_animation
#   File "<maya console>", line 374, in create_keyframes
# #   File "C:\Users/swagg/Documents/maya/2023/scripts\textgrid\textgrid.py", line 807, in fromFile
    tg.read(f)
# #   File "C:\Users/swagg/Documents/maya/2023/scripts\textgrid\textgrid.py", line 698, in read
    encoding = detectEncoding(f)
# #   File "C:\Users/swagg/Documents/maya/2023/scripts\textgrid\textgrid.py", line 87, in detectEncoding
    with codecs.open(f, 'r', encoding='utf-16') as source:
# #   File "D:\AutoDesk/Maya2023\Python\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
# FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by Swaggymcmuffins** [comment]
b"'mfa_align.exe' is not recognized as an internal or external command,\r\n"
b'operable program or batch file.\r\n'
Traceback (most recent call last):
File "<maya console>", line 323, in generate_animation
 File "<maya console>", line 374, in create_keyframes
File "C:\Users/swagg/Documents/maya/2023/scripts\textgrid\textgrid.py", line 807, in fromFile
    tg.read(f)
"C:\Users/swagg/Documents/maya/2023/scripts\textgrid\textgrid.py", line 698, in read
    encoding = detectEncoding(f)
File "C:\Users/swagg/Documents/maya/2023/scripts\textgrid\textgrid.py", line 87, in detectEncoding
    with codecs.open(f, 'r', encoding='utf-16') as source:
File "D:\AutoDesk/Maya2023\Python\lib\codecs.py", line 905, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: ''

without the hashes^

**Comment by adamgravois** [comment]
Did you install the other scripts as shown in https://github.com/joaen/maya-auto-lip-sync#dependencies ? 
`"'mfa_align.exe' is not recognized as an internal or external command"` means it cant find the Montreal Forced Aligner tool. The script needs that and TextGrid and the lexicon ... fortunately (hopefully) these are a one-click install

**Comment by Swaggymcmuffins** [comment]
> Did you install the other scripts as shown in https://github.com/joaen/maya-auto-lip-sync#dependencies ? `"'mfa_align.exe' is not recognized as an internal or external command"` means it cant find the Montreal Forced Aligner tool. The script needs that and TextGrid and the lexicon ... fortunately (hopefully) these are a one-click install

I did yeah, tried both manual as well as the automatic one that is supplied in the files, had a more tech savvy with Maya person check them out as well and he said the referenced files are all there so he doesn't know why it wouldn't work.

**Comment by adamgravois** [comment]
Huh. why won't it see the .exe? Weird.

Some more checklist-type questions: 
What version of Maya are you running? I'm using 2022.4
is this what your documents/maya/202x/scripts directory looks like?
<img width="279" alt="image" src="https://github.com/joaen/maya-auto-lip-sync/assets/68667824/d92e0677-6d6a-4b53-b654-6f2c4fad5674">
<img width="242" alt="image" src="https://github.com/joaen/maya-auto-lip-sync/assets/68667824/5cc0341e-e3b5-4b94-8a5c-6f249c49dfd2">

**Comment by Swaggymcmuffins** [comment]
![image_2023-11-28_103123298](https://github.com/joaen/maya-auto-lip-sync/assets/47432333/feeaf4d1-efb7-4538-90b9-d1376a098ddc)
![Screenshot 2023-11-28 103056](https://github.com/joaen/maya-auto-lip-sync/assets/47432333/0f97d4d6-a157-4702-a7ae-d81d77de1d25)

I'm using maya 2023.3, I've attached my screengrabs as well, they seem to be matching yours, I hope that helps!

**Comment by adamgravois** [comment]
sorry I'm out of suggestions. maybe its a path or permissions problem? This is the point where I start flailing 😅

**Comment by Rana2877** [comment]
Antivirus is blocking the .bat file in my case.
